version: '3.7'
services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db_student'      
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:      
      - '3307:3306'
    expose:
      - '3307'
